version: "3.7"
services:

  server-auth:
    build:      
      context: ./
      dockerfile: ./docker/Dockerfile    
    image: server-auth
    container_name: server-auth
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - server-auth
  nginx-auth:
    image: nginx:1.22-alpine
    container_name: nginx-auth
    ports:
      - 80:80
    depends_on:
      - server-auth
    volumes:
      - ./:/var/www
      - ./docker/nginx-conf.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - server-auth

networks:
  server-auth:
    driver: bridge