version: "3.7"
services:

  server-sciweb:
    build:      
      context: ./
      dockerfile: ./docker/Dockerfile    
    image: server-sciweb
    container_name: server-sciweb
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - server-sciweb
  nginx-server-sciweb:
    image: nginx:1.22-alpine
    container_name: nginx-server-sciweb
    ports:
      - 8001:80
    depends_on:
      - server-sciweb
    volumes:
      - ./:/var/www
      - ./docker/nginx-conf.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - server-sciweb

networks:
  server-sciweb:
    driver: bridge