version: "3.7"
services:

  server-rhnet:
    build:      
      context: ./
      dockerfile: ./docker/Dockerfile    
    image: server-rhnet
    container_name: server-rhnet
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - server-rhnet
  nginx-server-rhnet:
    image: nginx:1.22-alpine
    container_name: nginx-server-rhnet
    ports:
      - 8002:80
    depends_on:
      - server-rhnet
    volumes:
      - ./:/var/www
      - ./docker/nginx-conf.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - server-rhnet

networks:
  server-rhnet:
    driver: bridge